# Generated by Django 5.0.7 on 2024-07-15 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices_comparator_tool', '0002_productcategory_product_produc_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='produc_price',
            new_name='product_price',
        ),
    ]
