# Generated by Django 5.0.7 on 2024-07-15 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices_comparator_tool', '0003_rename_produc_price_product_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_unis',
            new_name='total_units',
        ),
    ]
