# Generated by Django 5.0.7 on 2024-07-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices_comparator_tool', '0004_rename_total_unis_product_total_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='units',
            field=models.CharField(choices=[('LONGITUDE', 'LONGITUDE'), ('VOLUME', 'VOLUME'), ('WEIGHT', 'WEIGHT')], default='LONGITUDE', max_length=10),
        ),
    ]
