# Generated by Django 5.0.7 on 2024-07-17 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices_comparator_tool', '0006_rename_product_weight_product_product_weight_volume_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='units',
            new_name='measure_units',
        ),
    ]
